# Default values for bkpcheck-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: registry.its-k8s-dev.swatchgroup.net/common/launchmp
  #pullPolicy: IfNotPresent
  pullPolicy: Always

imagePullSecrets:
  - name: harborprod

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: true
  route: true
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"

  enablemiddlewares: false
  hosts:
    - host: launchmp.its-k8s-dev.swatchgroup.net
      paths: [/]
      middlewares:
        - name: middle1
        - name: middle2
  tls:
    - secretName: ingresstls
  #    hosts:
  #      - chart-example.local

ntx:
  user: ""
  password: ""


nodeSelector: {}

tolerations: []

affinity: {}
