apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ template "launchmp-helm.fullname" . }}
  labels:
  {{- include "launchmp-helm.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
  {{- include "launchmp-helm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
    {{- include "launchmp-helm.labels" . | nindent 10 }}
    spec:
      terminationGracePeriodSeconds: 10
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 12 }}
      {{- end }}
      containers:
        - name: launchmp
          image: {{.Values.image.repository}}:{{.Chart.AppVersion}}
          imagePullPolicy: {{.Values.image.pullPolicy}}
          readinessProbe:
            httpGet:
              path: /health
              port: 5000
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 5000
              scheme: HTTPS
            initialDelaySeconds: 15
            periodSeconds: 20

          resources:
            limits:
              memory:  500Mi
            requests:
              memory: 200Mi
          ports:
            - containerPort: 5000
          command: ["gunicorn"]
          args: ["-w 1", "-b 0.0.0.0:5000" , "run:app"]
          env:
            - name: NTX_USER
              valueFrom:
                secretKeyRef:
                  key: ntx-user
                  name: launchmp
            - name: NTX_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: db-password
                  name: launchmp
            - name: VERSION
              value: {{.Chart.AppVersion}}
